# ==============================================================================
# Merged Lakeflow Source: azure_servicebus
# ==============================================================================
# This file is auto-generated by tools/scripts/merge_python_source.py
# Do not edit manually. Make changes to the source files instead.
# ==============================================================================

from datetime import datetime
from decimal import Decimal
from typing import (
    Any,
    Callable,
    Iterator,
    Optional,
    TypeVar,
)
import json
import time

from azure.core.exceptions import (
    ClientAuthenticationError,
    HttpResponseError,
    ServiceRequestError,
    ServiceResponseError,
)
from azure.identity import ClientSecretCredential, DefaultAzureCredential, ManagedIdentityCredential
from azure.servicebus import ServiceBusClient, ServiceBusSessionFilter, ServiceBusSubQueue
from azure.servicebus.exceptions import (
    MessageSizeExceededError,
    OperationTimeoutError,
    ServiceBusAuthenticationError,
    ServiceBusAuthorizationError,
    ServiceBusConnectionError,
    ServiceBusError,
)
from azure.servicebus.management import ServiceBusAdministrationClient
from pyspark.sql import Row
from pyspark.sql.datasource import DataSource, DataSourceReader, SimpleDataSourceStreamReader
from pyspark.sql.types import *
import base64
import logging


def register_lakeflow_source(spark):
    """Register the Lakeflow Python source with Spark."""

    ########################################################
    # src/databricks/labs/community_connector/libs/utils.py
    ########################################################

    def _parse_struct(value: Any, field_type: StructType) -> Row:
        """Parse a dictionary into a PySpark Row based on StructType schema."""
        if not isinstance(value, dict):
            raise ValueError(f"Expected a dictionary for StructType, got {type(value)}")
        # Spark Python -> Arrow conversion require missing StructType fields to be assigned None.
        if value == {}:
            raise ValueError(
                "field in StructType cannot be an empty dict. "
                "Please assign None as the default value instead."
            )
        field_dict = {}
        for field in field_type.fields:
            if field.name in value:
                field_dict[field.name] = parse_value(value.get(field.name), field.dataType)
            elif field.nullable:
                field_dict[field.name] = None
            else:
                raise ValueError(f"Field {field.name} is not nullable but not found in the input")
        return Row(**field_dict)


    def _parse_array(value: Any, field_type: ArrayType) -> list:
        """Parse a list into a PySpark array based on ArrayType schema."""
        if not isinstance(value, list):
            if field_type.containsNull:
                return [parse_value(value, field_type.elementType)]
            raise ValueError(f"Expected a list for ArrayType, got {type(value)}")
        return [parse_value(v, field_type.elementType) for v in value]


    def _parse_map(value: Any, field_type: MapType) -> dict:
        """Parse a dictionary into a PySpark map based on MapType schema."""
        if not isinstance(value, dict):
            raise ValueError(f"Expected a dictionary for MapType, got {type(value)}")
        return {
            parse_value(k, field_type.keyType): parse_value(v, field_type.valueType)
            for k, v in value.items()
        }


    def _parse_string(value: Any) -> str:
        """Convert value to string."""
        return str(value)


    def _parse_integer(value: Any) -> int:
        """Convert value to integer."""
        if isinstance(value, str) and value.strip():
            return int(float(value)) if "." in value else int(value)
        if isinstance(value, (int, float)):
            return int(value)
        raise ValueError(f"Cannot convert {value} to integer")


    def _parse_float(value: Any) -> float:
        """Convert value to float."""
        return float(value)


    def _parse_decimal(value: Any) -> Decimal:
        """Convert value to Decimal."""
        return Decimal(value) if isinstance(value, str) and value.strip() else Decimal(str(value))


    def _parse_boolean(value: Any) -> bool:
        """Convert value to boolean."""
        if isinstance(value, str):
            lowered = value.lower()
            if lowered in ("true", "t", "yes", "y", "1"):
                return True
            if lowered in ("false", "f", "no", "n", "0"):
                return False
        return bool(value)


    def _parse_date(value: Any) -> datetime.date:
        """Convert value to date."""
        if isinstance(value, str):
            for fmt in ("%Y-%m-%d", "%m/%d/%Y", "%d-%m-%Y", "%Y/%m/%d"):
                try:
                    return datetime.strptime(value, fmt).date()
                except ValueError:
                    continue
            return datetime.fromisoformat(value).date()
        if isinstance(value, datetime):
            return value.date()
        raise ValueError(f"Cannot convert {value} to date")


    def _parse_timestamp(value: Any) -> datetime:
        """Convert value to timestamp."""
        if isinstance(value, str):
            ts_value = value.replace("Z", "+00:00") if value.endswith("Z") else value
            try:
                return datetime.fromisoformat(ts_value)
            except ValueError:
                for fmt in ("%Y-%m-%d %H:%M:%S", "%Y/%m/%d %H:%M:%S"):
                    try:
                        return datetime.strptime(ts_value, fmt)
                    except ValueError:
                        continue
        elif isinstance(value, (int, float)):
            return datetime.fromtimestamp(value)
        elif isinstance(value, datetime):
            return value
        raise ValueError(f"Cannot convert {value} to timestamp")


    def _decode_string_to_bytes(value: str) -> bytes:
        """Try to decode a string as base64, then hex, then UTF-8."""
        try:
            return base64.b64decode(value)
        except Exception:
            pass
        try:
            return bytes.fromhex(value)
        except Exception:
            pass
        return value.encode("utf-8")


    def _parse_binary(value: Any) -> bytes:
        """Convert value to bytes. Tries base64, then hex, then UTF-8 for strings."""
        if isinstance(value, bytes):
            return value
        if isinstance(value, bytearray):
            return bytes(value)
        if isinstance(value, str):
            return _decode_string_to_bytes(value)
        if isinstance(value, list):
            return bytes(value)
        return str(value).encode("utf-8")


    # Mapping of primitive types to their parser functions
    _PRIMITIVE_PARSERS = {
        StringType: _parse_string,
        IntegerType: _parse_integer,
        LongType: _parse_integer,
        FloatType: _parse_float,
        DoubleType: _parse_float,
        DecimalType: _parse_decimal,
        BooleanType: _parse_boolean,
        DateType: _parse_date,
        TimestampType: _parse_timestamp,
        BinaryType: _parse_binary,
    }


    def parse_value(value: Any, field_type: DataType) -> Any:
        """
        Converts a JSON value into a PySpark-compatible data type based on the provided field type.
        """
        if value is None:
            return None

        # Handle complex types
        if isinstance(field_type, StructType):
            return _parse_struct(value, field_type)
        if isinstance(field_type, ArrayType):
            return _parse_array(value, field_type)
        if isinstance(field_type, MapType):
            return _parse_map(value, field_type)

        # Handle primitive types via type-based lookup
        try:
            field_type_class = type(field_type)
            if field_type_class in _PRIMITIVE_PARSERS:
                return _PRIMITIVE_PARSERS[field_type_class](value)

            # Check for custom UDT handling
            if hasattr(field_type, "fromJson"):
                return field_type.fromJson(value)

            raise TypeError(f"Unsupported field type: {field_type}")
        except (ValueError, TypeError) as e:
            raise ValueError(f"Error converting '{value}' ({type(value)}) to {field_type}: {str(e)}")


    ########################################################
    # src/databricks/labs/community_connector/interface/lakeflow_connect.py
    ########################################################

    class LakeflowConnect:
        def __init__(self, options: dict[str, str]) -> None:
            """
            Initialize the source connector with parameters needed to connect to the source.
            Args:
                options: A dictionary of parameters like authentication tokens, table names,
                    and other configurations.
            """

        def list_tables(self) -> list[str]:
            """
            List names of all the tables supported by the source connector.
            The list could either be a static list or retrieved from the source via API.
            Returns:
                A list of table names.
            """

        def get_table_schema(
            self, table_name: str, table_options: dict[str, str]
        ) -> StructType:
            """
            Fetch the schema of a table.
            Args:
                table_name: The name of the table to fetch the schema for.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to fetch the schema.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A StructType object representing the schema of the table.
            """

        def read_table_metadata(
            self, table_name: str, table_options: dict[str, str]
        ) -> dict:
            """
            Fetch the metadata of a table.
            Args:
                table_name: The name of the table to fetch the metadata for.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to fetch the metadata.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A dictionary containing the metadata of the table. It should include the
                following keys:
                    - primary_keys: List of string names of the primary key columns of
                        the table.
                    - cursor_field: The name of the field to use as a cursor for
                        incremental loading.
                    - ingestion_type: The type of ingestion to use for the table. It
                        should be one of the following values:
                        - "snapshot": For snapshot loading.
                        - "cdc": Capture incremental changes (no delete support).
                        - "cdc_with_deletes": Capture incremental changes with delete
                            support. Requires implementing read_table_deletes().
                        - "append": Incremental append.
            """

        def read_table(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> (Iterator[dict], dict):
            """
            Read the records of a table and return an iterator of records and an offset.
            The read starts from the provided start_offset.
            Records returned in the iterator will be one batch of records marked by the
            offset as its end_offset.
            The read_table function could be called multiple times to read the entire table
            in multiple batches and it stops when the same offset is returned again.
            If the table cannot be incrementally read, the offset can be None if we want to
            read the entire table in one batch.
            We could still return some fake offsets (cannot checkpointing) to split the
            table into multiple batches.
            Args:
                table_name: The name of the table to read.
                start_offset: The offset to start reading from.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to read the table.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                An iterator of records in JSON format and an offset.
                DO NOT convert the JSON based on the schema in `get_table_schema` in
                `read_table`.
                records: An iterator of records in JSON format.
                offset: An offset in dict.
            """

        def read_table_deletes(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> (Iterator[dict], dict):
            """
            Read deleted records from a table for CDC delete synchronization.
            This method is called when ingestion_type is "cdc_with_deletes" to fetch
            records that have been deleted from the source system.

            The returned records should have at minimum the primary key fields and
            cursor field populated. Other fields can be null.

            Args:
                table_name: The name of the table to read deleted records from.
                start_offset: The offset to start reading from (same format as read_table).
                table_options: A dictionary of options for accessing the table.
            Returns:
                An iterator of deleted records in JSON format and an offset.
                records: An iterator of deleted records (must include primary keys and cursor).
                offset: An offset in dict (same format as read_table).
            """


    ########################################################
    # src/databricks/labs/community_connector/sources/azure_servicebus/azure_servicebus.py
    ########################################################

    logger = logging.getLogger(__name__)

    T = TypeVar("T")


    # ---------------------------------------------------------------------------
    # Retry helper
    # ---------------------------------------------------------------------------

    _TRANSIENT_EXCEPTIONS = (
        ServiceBusConnectionError,
        OperationTimeoutError,
        ServiceRequestError,
        ServiceResponseError,
        ConnectionError,
        TimeoutError,
        OSError,
    )


    def _is_transient(exc: Exception) -> bool:
        """Return True if the exception is transient and the operation can be retried."""
        if isinstance(exc, _TRANSIENT_EXCEPTIONS):
            return True
        if isinstance(exc, HttpResponseError):
            return exc.status_code in (408, 429, 500, 502, 503, 504)
        if isinstance(exc, ServiceBusError):
            msg = str(exc).lower()
            return any(kw in msg for kw in ("timeout", "busy", "throttl", "temporary"))
        return False


    def _retry_with_backoff(
        func: Callable[[], T],
        *,
        max_retries: int = 3,
        base_delay: float = 1.0,
        max_delay: float = 30.0,
        operation_name: str = "",
    ) -> T:
        """
        Execute *func* with retry + exponential backoff for transient failures.
        Non-transient exceptions are raised immediately.
        """
        last_exc: Optional[Exception] = None
        for attempt in range(max_retries + 1):
            try:
                return func()
            except Exception as exc:
                last_exc = exc
                if attempt == max_retries or not _is_transient(exc):
                    raise
                delay = min(base_delay * (2 ** attempt), max_delay)
                logger.warning(
                    "[Retry %d/%d] %s failed (%s: %s), retrying in %.1fs",
                    attempt + 1,
                    max_retries,
                    operation_name or "Operation",
                    type(exc).__name__,
                    exc,
                    delay,
                )
                time.sleep(delay)
        # Should not reach here, but satisfy the type checker
        raise last_exc  # type: ignore[misc]


    class AzureServicebusLakeflowConnect(LakeflowConnect):  # pylint: disable=too-many-instance-attributes
        """
        Azure Service Bus connector implementing the Lakeflow Community Connector interface.
        """

        # Supported tables
        SUPPORTED_TABLES = [
            "queues",
            "topics",
            "subscriptions",
            "queue_messages",
            "subscription_messages",
            "dead_letter_messages",
        ]

        # Tables that require incremental ingestion
        INCREMENTAL_TABLES = [
            "queue_messages",
            "subscription_messages",
            "dead_letter_messages",
        ]

        def __init__(self, options: dict[str, str]) -> None:
            """
            Initialize the Azure Service Bus connector.

            Args:
                options: Dictionary containing connection parameters:
                    - connection_string: Full Service Bus connection string (option 1)
                    - fully_qualified_namespace: Namespace URL for Azure AD auth (option 2)
                    - credential_type: 'connection_string', 'azure_ad', 'service_principal',
                                       or 'managed_identity' (default: auto-detect)
                    - operation_timeout: Timeout in seconds for SDK operations (default: 60)
                    - max_wait_time: Max wait time in seconds for receivers (default: 5)
                    - max_retries: Max retry attempts for transient failures (default: 3)
                    - max_body_size: Max body size in bytes before truncation (default: 0 = unlimited)
                    - debug_mode: 'true' to enable verbose per-message logging (default: 'false')

                    For service_principal credential_type:
                    - azure_tenant_id: Azure AD tenant ID
                    - azure_client_id: Service principal client/application ID
                    - azure_client_secret: Service principal client secret

                    For managed_identity credential_type:
                    - azure_client_id: (Optional) Client ID for user-assigned managed identity
            """
            self.options = options
            self._admin_client: Optional[ServiceBusAdministrationClient] = None
            self._client: Optional[ServiceBusClient] = None
            self._credential = None
            self._closed = False

            # Configurable timeouts and retry
            self.operation_timeout = int(options.get("operation_timeout", "60"))
            self.max_wait_time = int(options.get("max_wait_time", "5"))
            self.max_retries = int(options.get("max_retries", "3"))
            self.max_body_size = int(options.get("max_body_size", "0"))
            self.debug_mode = options.get("debug_mode", "false").lower() == "true"

            # Determine authentication method
            self.connection_string = options.get("connection_string")
            self.fully_qualified_namespace = options.get("fully_qualified_namespace")
            self.credential_type = options.get("credential_type", "auto")

            # Azure AD / Service Principal options
            self.azure_tenant_id = options.get("azure_tenant_id")
            self.azure_client_id = options.get("azure_client_id")
            self.azure_client_secret = options.get("azure_client_secret")

            if self.credential_type == "auto":
                if self.connection_string:
                    self.credential_type = "connection_string"
                elif (
                    self.azure_tenant_id
                    and self.azure_client_id
                    and self.azure_client_secret
                ):
                    self.credential_type = "service_principal"
                elif self.fully_qualified_namespace:
                    self.credential_type = "azure_ad"
                else:
                    raise ValueError(
                        "Either 'connection_string' or 'fully_qualified_namespace' must be provided. "
                        "For Azure AD authentication, provide 'fully_qualified_namespace'. "
                        "For service principal, also provide 'azure_tenant_id', 'azure_client_id', "
                        "and 'azure_client_secret'."
                    )

            # Initialize clients
            self._init_clients()

        def _init_clients(self) -> None:
            """Initialize Service Bus clients based on credential type."""
            if self.credential_type == "connection_string":
                self._init_connection_string_auth()
            elif self.credential_type == "service_principal":
                self._init_service_principal_auth()
            elif self.credential_type == "managed_identity":
                self._init_managed_identity_auth()
            elif self.credential_type == "azure_ad":
                self._init_azure_ad_auth()
            else:
                raise ValueError(f"Unsupported credential_type: {self.credential_type}")

        def _init_connection_string_auth(self) -> None:
            """Initialize clients using connection string authentication."""
            if not self.connection_string:
                raise ValueError(
                    "connection_string is required for connection_string auth"
                )
            try:
                self._admin_client = (
                    ServiceBusAdministrationClient.from_connection_string(
                        self.connection_string
                    )
                )
                self._client = ServiceBusClient.from_connection_string(
                    self.connection_string,
                    socket_timeout=self.operation_timeout,
                )
            except Exception as e:
                raise ValueError(
                    f"Failed to initialize Service Bus client with connection string. "
                    f"Ensure the connection string is valid and includes the SharedAccessKey. "
                    f"Error: {e}"
                ) from e

        def _init_service_principal_auth(self) -> None:
            """Initialize clients using service principal (client credentials) authentication."""
            if not self.fully_qualified_namespace:
                raise ValueError(
                    "fully_qualified_namespace is required for service_principal auth"
                )
            if not all(
                [self.azure_tenant_id, self.azure_client_id, self.azure_client_secret]
            ):
                raise ValueError(
                    "azure_tenant_id, azure_client_id, and azure_client_secret are all required "
                    "for service_principal authentication"
                )

            try:
                self._credential = ClientSecretCredential(
                    tenant_id=self.azure_tenant_id,
                    client_id=self.azure_client_id,
                    client_secret=self.azure_client_secret,
                )
                self._create_clients_with_credential(self._credential)
            except ClientAuthenticationError as e:
                raise ValueError(
                    f"Service principal authentication failed. Please verify:\n"
                    f"  1. azure_tenant_id is correct: {self.azure_tenant_id}\n"
                    f"  2. azure_client_id is correct: {self.azure_client_id}\n"
                    f"  3. azure_client_secret is valid and not expired\n"
                    f"  4. The service principal has required RBAC roles on the Service Bus namespace:\n"
                    f"     - 'Azure Service Bus Data Receiver' or 'Azure Service Bus Data Owner'\n"
                    f"     - 'Reader' role for management operations\n"
                    f"Error: {e}"
                ) from e
            except Exception as e:
                raise ValueError(
                    f"Failed to initialize Service Bus client with service principal. Error: {e}"
                ) from e

        def _init_managed_identity_auth(self) -> None:
            """Initialize clients using managed identity authentication."""
            if not self.fully_qualified_namespace:
                raise ValueError(
                    "fully_qualified_namespace is required for managed_identity auth"
                )

            try:
                if self.azure_client_id:
                    self._credential = ManagedIdentityCredential(
                        client_id=self.azure_client_id
                    )
                    logger.info(
                        f"Using user-assigned managed identity: {self.azure_client_id}"
                    )
                else:
                    self._credential = ManagedIdentityCredential()
                    logger.info("Using system-assigned managed identity")

                self._create_clients_with_credential(self._credential)
            except ClientAuthenticationError as e:
                error_msg = (
                    f"Managed identity authentication failed. Please verify:\n"
                    f"  1. This code is running in an Azure environment with managed identity enabled\n"
                    f"  2. The managed identity has required RBAC roles on the Service Bus namespace:\n"
                    f"     - 'Azure Service Bus Data Receiver' or 'Azure Service Bus Data Owner'\n"
                    f"     - 'Reader' role for management operations\n"
                )
                if self.azure_client_id:
                    error_msg += (
                        f"  3. User-assigned managed identity client_id"
                        f" is correct: {self.azure_client_id}\n"
                    )
                error_msg += f"Error: {e}"
                raise ValueError(error_msg) from e
            except Exception as e:
                raise ValueError(
                    f"Failed to initialize Service Bus client with managed identity. "
                    f"Ensure you are running in an Azure environment with managed identity enabled. "
                    f"Error: {e}"
                ) from e

        def _init_azure_ad_auth(self) -> None:
            """Initialize clients using Azure AD DefaultAzureCredential authentication."""
            if not self.fully_qualified_namespace:
                raise ValueError(
                    "fully_qualified_namespace is required for azure_ad auth"
                )

            try:
                self._credential = DefaultAzureCredential()
                self._create_clients_with_credential(self._credential)
            except ClientAuthenticationError as e:
                raise ValueError(
                    f"Azure AD authentication failed. Please ensure one of the following:\n"
                    f"  1. Run 'az login' to authenticate with Azure CLI\n"
                    f"  2. Set environment variables: AZURE_CLIENT_ID, AZURE_TENANT_ID, AZURE_CLIENT_SECRET\n"
                    f"  3. Use managed identity in Azure environment\n"
                    f"  4. Use service_principal credential_type with explicit credentials\n\n"
                    f"After authenticating, ensure the identity has required RBAC roles:\n"
                    f"  - 'Azure Service Bus Data Receiver' or 'Azure Service Bus Data Owner'\n"
                    f"  - 'Reader' role for management operations\n"
                    f"Error: {e}"
                ) from e
            except Exception as e:
                error_str = str(e).lower()
                if "no credential" in error_str or "defaultazurecredential" in error_str:
                    raise ValueError(
                        f"No Azure credentials found. Please authenticate using one of:\n"
                        f"  1. Azure CLI: Run 'az login' and 'az account set -s <subscription-id>'\n"
                        f"  2. Environment variables: Set AZURE_CLIENT_ID, AZURE_TENANT_ID, AZURE_CLIENT_SECRET\n"
                        f"  3. Managed Identity: Deploy to Azure with managed identity enabled\n"
                        f"  4. Service Principal: Use credential_type='service_principal' with explicit credentials\n"
                        f"Error: {e}"
                    ) from e
                raise ValueError(
                    f"Failed to initialize Service Bus client with Azure AD. Error: {e}"
                ) from e

        def _create_clients_with_credential(self, credential) -> None:
            """Create Service Bus clients with the given credential."""
            try:
                self._admin_client = ServiceBusAdministrationClient(
                    self.fully_qualified_namespace, credential
                )
                self._client = ServiceBusClient(
                    self.fully_qualified_namespace, credential,
                    socket_timeout=self.operation_timeout,
                )

                # Validate the connection by making a simple API call
                self._validate_connection()
            except ClientAuthenticationError:
                raise
            except Exception as e:
                error_str = str(e).lower()
                if "unauthorized" in error_str or "403" in error_str:
                    raise ValueError(
                        f"Authorization failed. The authenticated identity does not have required permissions.\n"
                        f"Assign these RBAC roles to the identity on the Service Bus namespace:\n"
                        f"  - 'Azure Service Bus Data Receiver' for reading messages\n"
                        f"  - 'Azure Service Bus Data Owner' for full access\n"
                        f"  - 'Reader' for listing queues/topics\n"
                        f"Namespace: {self.fully_qualified_namespace}\n"
                        f"Error: {e}"
                    ) from e
                raise

        def _validate_connection(self) -> None:
            """Validate the connection by making a test API call."""
            try:
                next(iter(self._admin_client.list_queues()), None)
                logger.info(
                    f"Successfully connected to Service Bus namespace: "
                    f"{self.fully_qualified_namespace}"
                )
            except ClientAuthenticationError:
                raise
            except Exception as e:
                error_str = str(e).lower()
                if (
                    "unauthorized" in error_str
                    or "403" in error_str
                    or "forbidden" in error_str
                ):
                    raise ValueError(
                        f"Connected to Service Bus but authorization failed.\n"
                        f"The identity can authenticate but lacks permissions on namespace: "
                        f"{self.fully_qualified_namespace}\n"
                        f"Required RBAC roles:\n"
                        f"  - 'Reader' or 'Contributor' for management operations\n"
                        f"  - 'Azure Service Bus Data Receiver' for reading messages\n"
                        f"Error: {e}"
                    ) from e
                logger.warning(f"Could not validate connection: {e}")
                raise RuntimeError(
                    f"Failed to validate connection to Service Bus namespace "
                    f"'{self.fully_qualified_namespace}': {e}"
                ) from e

        # =========================================================================
        # Health Check
        # =========================================================================

        def health_check(self) -> dict:
            """
            Check the health of the connection.

            Returns:
                Dictionary with 'healthy' (bool) and 'details' (str).
            """
            if self._closed:
                return {"healthy": False, "details": "Connector has been closed."}
            try:
                queues = list(self._admin_client.list_queues())
                return {
                    "healthy": True,
                    "details": f"Connected. {len(queues)} queue(s) accessible.",
                }
            except Exception as e:
                return {"healthy": False, "details": f"Connection error: {e}"}

        def list_tables(self) -> list[str]:
            """
            List all supported tables.

            Returns:
                List of table names supported by this connector.
            """
            return self.SUPPORTED_TABLES.copy()

        def get_table_schema(
            self, table_name: str, table_options: dict[str, str]
        ) -> StructType:
            """
            Get the schema for a table.

            Args:
                table_name: Name of the table
                table_options: Additional options for the table

            Returns:
                StructType representing the table schema
            """
            if table_name not in self.SUPPORTED_TABLES:
                raise ValueError(f"Unsupported table: {table_name}")

            schemas = {
                "queues": self._get_queues_schema(),
                "topics": self._get_topics_schema(),
                "subscriptions": self._get_subscriptions_schema(),
                "queue_messages": self._get_queue_messages_schema(),
                "subscription_messages": self._get_subscription_messages_schema(),
                "dead_letter_messages": self._get_dead_letter_messages_schema(),
            }

            return schemas[table_name]

        def read_table_metadata(
            self, table_name: str, table_options: dict[str, str]
        ) -> dict:
            """
            Get metadata for a table including primary keys and ingestion type.

            Args:
                table_name: Name of the table
                table_options: Additional options for the table

            Returns:
                Dictionary with primary_keys, cursor_field, and ingestion_type
            """
            if table_name not in self.SUPPORTED_TABLES:
                raise ValueError(f"Unsupported table: {table_name}")

            metadata = {
                "queues": {
                    "primary_keys": ["name"],
                    "cursor_field": None,
                    "ingestion_type": "snapshot",
                },
                "topics": {
                    "primary_keys": ["name"],
                    "cursor_field": None,
                    "ingestion_type": "snapshot",
                },
                "subscriptions": {
                    "primary_keys": ["topic_name", "name"],
                    "cursor_field": None,
                    "ingestion_type": "snapshot",
                },
                "queue_messages": {
                    "primary_keys": ["queue_name", "sequence_number"],
                    "cursor_field": "sequence_number",
                    "ingestion_type": "append",
                },
                "subscription_messages": {
                    "primary_keys": [
                        "topic_name",
                        "subscription_name",
                        "sequence_number",
                    ],
                    "cursor_field": "sequence_number",
                    "ingestion_type": "append",
                },
                "dead_letter_messages": {
                    "primary_keys": ["source_type", "source_name", "sequence_number"],
                    "cursor_field": "sequence_number",
                    "ingestion_type": "append",
                },
            }

            return metadata[table_name]

        def read_table(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """
            Read records from a table.

            Args:
                table_name: Name of the table to read
                start_offset: Starting offset for incremental reads
                table_options: Additional options for the table

            Returns:
                Tuple of (iterator of records, next offset)
            """
            if table_name not in self.SUPPORTED_TABLES:
                raise ValueError(f"Unsupported table: {table_name}")

            readers = {
                "queues": self._read_queues,
                "topics": self._read_topics,
                "subscriptions": self._read_subscriptions,
                "queue_messages": self._read_queue_messages,
                "subscription_messages": self._read_subscription_messages,
                "dead_letter_messages": self._read_dead_letter_messages,
            }

            return readers[table_name](start_offset, table_options)

        # =========================================================================
        # Schema Definitions
        # =========================================================================

        def _get_queues_schema(self) -> StructType:
            """Schema for queues table."""
            return StructType(
                [
                    StructField("name", StringType(), False),
                    StructField("id", StringType(), True),
                    StructField("lock_duration", StringType(), True),
                    StructField("max_size_in_megabytes", LongType(), True),
                    StructField("requires_duplicate_detection", BooleanType(), True),
                    StructField("requires_session", BooleanType(), True),
                    StructField("default_message_time_to_live", StringType(), True),
                    StructField(
                        "dead_lettering_on_message_expiration", BooleanType(), True
                    ),
                    StructField(
                        "duplicate_detection_history_time_window", StringType(), True
                    ),
                    StructField("max_delivery_count", LongType(), True),
                    StructField("status", StringType(), True),
                    StructField("enable_batched_operations", BooleanType(), True),
                    StructField("auto_delete_on_idle", StringType(), True),
                    StructField("enable_partitioning", BooleanType(), True),
                    StructField("message_count", LongType(), True),
                    StructField("size_in_bytes", LongType(), True),
                    StructField("created_at", TimestampType(), True),
                    StructField("updated_at", TimestampType(), True),
                    StructField("accessed_at", TimestampType(), True),
                ]
            )

        def _get_topics_schema(self) -> StructType:
            """Schema for topics table."""
            return StructType(
                [
                    StructField("name", StringType(), False),
                    StructField("id", StringType(), True),
                    StructField("default_message_time_to_live", StringType(), True),
                    StructField("max_size_in_megabytes", LongType(), True),
                    StructField("requires_duplicate_detection", BooleanType(), True),
                    StructField(
                        "duplicate_detection_history_time_window", StringType(), True
                    ),
                    StructField("enable_batched_operations", BooleanType(), True),
                    StructField("status", StringType(), True),
                    StructField("support_ordering", BooleanType(), True),
                    StructField("auto_delete_on_idle", StringType(), True),
                    StructField("enable_partitioning", BooleanType(), True),
                    StructField("subscription_count", LongType(), True),
                    StructField("size_in_bytes", LongType(), True),
                    StructField("created_at", TimestampType(), True),
                    StructField("updated_at", TimestampType(), True),
                    StructField("accessed_at", TimestampType(), True),
                ]
            )

        def _get_subscriptions_schema(self) -> StructType:
            """Schema for subscriptions table."""
            return StructType(
                [
                    StructField("name", StringType(), False),
                    StructField("topic_name", StringType(), False),
                    StructField("id", StringType(), True),
                    StructField("lock_duration", StringType(), True),
                    StructField("requires_session", BooleanType(), True),
                    StructField("default_message_time_to_live", StringType(), True),
                    StructField(
                        "dead_lettering_on_message_expiration", BooleanType(), True
                    ),
                    StructField(
                        "dead_lettering_on_filter_evaluation_exceptions",
                        BooleanType(),
                        True,
                    ),
                    StructField("message_count", LongType(), True),
                    StructField("max_delivery_count", LongType(), True),
                    StructField("status", StringType(), True),
                    StructField("enable_batched_operations", BooleanType(), True),
                    StructField("auto_delete_on_idle", StringType(), True),
                    StructField("forward_to", StringType(), True),
                    StructField(
                        "forward_dead_lettered_messages_to", StringType(), True
                    ),
                    StructField("created_at", TimestampType(), True),
                    StructField("updated_at", TimestampType(), True),
                    StructField("accessed_at", TimestampType(), True),
                ]
            )

        def _get_message_base_schema(self) -> list[StructField]:
            """Base schema fields for message tables."""
            return [
                StructField("sequence_number", LongType(), False),
                StructField("message_id", StringType(), True),
                StructField("body", StringType(), True),
                StructField("content_type", StringType(), True),
                StructField("correlation_id", StringType(), True),
                StructField("subject", StringType(), True),
                StructField("reply_to", StringType(), True),
                StructField("reply_to_session_id", StringType(), True),
                StructField("to", StringType(), True),
                StructField("time_to_live", StringType(), True),
                StructField("session_id", StringType(), True),
                StructField("partition_key", StringType(), True),
                StructField("scheduled_enqueue_time_utc", TimestampType(), True),
                StructField("enqueued_time_utc", TimestampType(), True),
                StructField("expires_at_utc", TimestampType(), True),
                StructField("enqueued_sequence_number", LongType(), True),
                StructField("dead_letter_source", StringType(), True),
                StructField("delivery_count", LongType(), True),
                StructField("lock_token", StringType(), True),
                StructField("locked_until_utc", TimestampType(), True),
                StructField("state", StringType(), True),
                StructField("application_properties", StringType(), True),
            ]

        def _get_queue_messages_schema(self) -> StructType:
            """Schema for queue_messages table."""
            fields = [StructField("queue_name", StringType(), False)]
            fields.extend(self._get_message_base_schema())
            return StructType(fields)

        def _get_subscription_messages_schema(self) -> StructType:
            """Schema for subscription_messages table."""
            fields = [
                StructField("topic_name", StringType(), False),
                StructField("subscription_name", StringType(), False),
            ]
            fields.extend(self._get_message_base_schema())
            return StructType(fields)

        def _get_dead_letter_messages_schema(self) -> StructType:
            """Schema for dead_letter_messages table."""
            fields = [
                StructField("source_type", StringType(), False),
                StructField("source_name", StringType(), False),
            ]
            fields.extend(self._get_message_base_schema())
            fields.extend(
                [
                    StructField("dead_letter_reason", StringType(), True),
                    StructField("dead_letter_error_description", StringType(), True),
                ]
            )
            return StructType(fields)

        # =========================================================================
        # Read Implementations
        # =========================================================================

        def _read_queues(
            self, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """Read queues from the namespace."""

            def generate_records():
                queues = _retry_with_backoff(
                    lambda: list(self._admin_client.list_queues()),
                    max_retries=self.max_retries,
                    operation_name="list_queues",
                )
                for queue in queues:
                    runtime_props = _retry_with_backoff(
                        lambda q=queue: self._admin_client.get_queue_runtime_properties(q.name),
                        max_retries=self.max_retries,
                        operation_name=f"get_queue_runtime_properties({queue.name})",
                    )
                    yield {
                        "name": queue.name,
                        "id": None,
                        "lock_duration": (
                            str(queue.lock_duration) if queue.lock_duration else None
                        ),
                        "max_size_in_megabytes": queue.max_size_in_megabytes,
                        "requires_duplicate_detection": queue.requires_duplicate_detection,
                        "requires_session": queue.requires_session,
                        "default_message_time_to_live": (
                            str(queue.default_message_time_to_live)
                            if queue.default_message_time_to_live
                            else None
                        ),
                        "dead_lettering_on_message_expiration": (
                            queue.dead_lettering_on_message_expiration
                        ),
                        "duplicate_detection_history_time_window": (
                            str(queue.duplicate_detection_history_time_window)
                            if queue.duplicate_detection_history_time_window
                            else None
                        ),
                        "max_delivery_count": queue.max_delivery_count,
                        "status": str(queue.status) if queue.status else None,
                        "enable_batched_operations": queue.enable_batched_operations,
                        "auto_delete_on_idle": (
                            str(queue.auto_delete_on_idle)
                            if queue.auto_delete_on_idle
                            else None
                        ),
                        "enable_partitioning": queue.enable_partitioning,
                        "message_count": runtime_props.total_message_count,
                        "size_in_bytes": runtime_props.size_in_bytes,
                        "created_at": runtime_props.created_at_utc,
                        "updated_at": runtime_props.updated_at_utc,
                        "accessed_at": runtime_props.accessed_at_utc,
                    }

            return generate_records(), {}

        def _read_topics(
            self, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """Read topics from the namespace."""

            def generate_records():
                topics = _retry_with_backoff(
                    lambda: list(self._admin_client.list_topics()),
                    max_retries=self.max_retries,
                    operation_name="list_topics",
                )
                for topic in topics:
                    runtime_props = _retry_with_backoff(
                        lambda t=topic: self._admin_client.get_topic_runtime_properties(t.name),
                        max_retries=self.max_retries,
                        operation_name=f"get_topic_runtime_properties({topic.name})",
                    )
                    yield {
                        "name": topic.name,
                        "id": None,
                        "default_message_time_to_live": (
                            str(topic.default_message_time_to_live)
                            if topic.default_message_time_to_live
                            else None
                        ),
                        "max_size_in_megabytes": topic.max_size_in_megabytes,
                        "requires_duplicate_detection": topic.requires_duplicate_detection,
                        "duplicate_detection_history_time_window": (
                            str(topic.duplicate_detection_history_time_window)
                            if topic.duplicate_detection_history_time_window
                            else None
                        ),
                        "enable_batched_operations": topic.enable_batched_operations,
                        "status": str(topic.status) if topic.status else None,
                        "support_ordering": topic.support_ordering,
                        "auto_delete_on_idle": (
                            str(topic.auto_delete_on_idle)
                            if topic.auto_delete_on_idle
                            else None
                        ),
                        "enable_partitioning": topic.enable_partitioning,
                        "subscription_count": runtime_props.subscription_count,
                        "size_in_bytes": runtime_props.size_in_bytes,
                        "created_at": runtime_props.created_at_utc,
                        "updated_at": runtime_props.updated_at_utc,
                        "accessed_at": runtime_props.accessed_at_utc,
                    }

            return generate_records(), {}

        def _read_subscriptions(
            self, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """Read subscriptions from topics."""
            topic_name = table_options.get("topic_name")

            def generate_records():
                if topic_name:
                    topics_to_read = [topic_name]
                else:
                    topics_to_read = _retry_with_backoff(
                        lambda: [t.name for t in self._admin_client.list_topics()],
                        max_retries=self.max_retries,
                        operation_name="list_topics_for_subscriptions",
                    )

                for t_name in topics_to_read:
                    subs = _retry_with_backoff(
                        lambda tn=t_name: list(self._admin_client.list_subscriptions(tn)),
                        max_retries=self.max_retries,
                        operation_name=f"list_subscriptions({t_name})",
                    )
                    for sub in subs:
                        runtime_props = _retry_with_backoff(
                            lambda tn=t_name, sn=sub.name: (
                                self._admin_client.get_subscription_runtime_properties(tn, sn)
                            ),
                            max_retries=self.max_retries,
                            operation_name=f"get_subscription_runtime_properties({t_name}/{sub.name})",
                        )
                        yield {
                            "name": sub.name,
                            "topic_name": t_name,
                            "id": None,
                            "lock_duration": (
                                str(sub.lock_duration) if sub.lock_duration else None
                            ),
                            "requires_session": sub.requires_session,
                            "default_message_time_to_live": (
                                str(sub.default_message_time_to_live)
                                if sub.default_message_time_to_live
                                else None
                            ),
                            "dead_lettering_on_message_expiration": (
                                sub.dead_lettering_on_message_expiration
                            ),
                            "dead_lettering_on_filter_evaluation_exceptions": (
                                sub.dead_lettering_on_filter_evaluation_exceptions
                            ),
                            "message_count": runtime_props.total_message_count,
                            "max_delivery_count": sub.max_delivery_count,
                            "status": str(sub.status) if sub.status else None,
                            "enable_batched_operations": sub.enable_batched_operations,
                            "auto_delete_on_idle": (
                                str(sub.auto_delete_on_idle)
                                if sub.auto_delete_on_idle
                                else None
                            ),
                            "forward_to": sub.forward_to,
                            "forward_dead_lettered_messages_to": sub.forward_dead_lettered_messages_to,
                            "created_at": runtime_props.created_at_utc,
                            "updated_at": runtime_props.updated_at_utc,
                            "accessed_at": runtime_props.accessed_at_utc,
                        }

            return generate_records(), {}

        def _peek_messages_with_retry(self, receiver, max_message_count, sequence_number, label="peek"):
            """Peek messages from a receiver with retry logic."""
            return _retry_with_backoff(
                lambda: receiver.peek_messages(
                    max_message_count=max_message_count,
                    sequence_number=sequence_number,
                ),
                max_retries=self.max_retries,
                operation_name=f"{label}(seq={sequence_number})",
            )

        def _peek_all_from_receiver(  # pylint: disable=too-many-arguments,too-many-positional-arguments
            self,
            receiver,
            max_message_count: int,
            start_sequence: int,
            queue_name: str,
            records: list,
            label: str,
        ) -> int:
            """Peek all messages from a single receiver, appending to *records*.

            Returns the last sequence number seen (or *start_sequence* if no
            messages were found).
            """
            last_sequence = start_sequence
            page_count = 0

            messages = self._peek_messages_with_retry(
                receiver,
                max_message_count,
                start_sequence + 1 if start_sequence else 0,
                label=label,
            )

            while messages:
                page_count += 1
                for msg in messages:
                    record = self._message_to_record(msg)
                    record["queue_name"] = queue_name
                    last_sequence = msg.sequence_number
                    records.append(record)
                    if self.debug_mode:
                        logger.debug(
                            "queue_messages[%s] seq=%d msg_id=%s",
                            queue_name,
                            msg.sequence_number,
                            msg.message_id,
                        )

                # Get next batch
                messages = self._peek_messages_with_retry(
                    receiver,
                    max_message_count,
                    last_sequence + 1,
                    label=label,
                )

            return last_sequence

        def _read_queue_messages(  # pylint: disable=too-many-locals,too-many-branches,too-many-statements
            self, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """Read messages from a queue using peek (non-destructive).

            Supports both regular and session-enabled queues.  For session
            queues the connector iterates through available sessions using
            ``NEXT_AVAILABLE`` and peeks messages from each one.  An explicit
            ``session_id`` table option can be provided to peek from a single
            session only.
            """
            queue_name = table_options.get("queue_name")
            if not queue_name:
                raise ValueError("queue_name is required for queue_messages table")

            max_message_count = int(table_options.get("max_message_count", "100"))
            start_sequence = start_offset.get("sequence_number", 0)
            session_id = table_options.get("session_id")  # optional

            last_sequence = start_sequence
            records: list[dict] = []
            t_start = time.perf_counter()

            try:
                if session_id:
                    # Explicit session requested
                    with self._client.get_queue_receiver(
                        queue_name, session_id=session_id
                    ) as receiver:
                        last_sequence = self._peek_all_from_receiver(
                            receiver, max_message_count, start_sequence,
                            queue_name, records,
                            label=f"peek_queue({queue_name}/session={session_id})",
                        )
                else:
                    # Try a regular (non-session) receiver first
                    try:
                        with self._client.get_queue_receiver(queue_name) as receiver:
                            last_sequence = self._peek_all_from_receiver(
                                receiver, max_message_count, start_sequence,
                                queue_name, records,
                                label=f"peek_queue({queue_name})",
                            )
                    except ServiceBusError as e:
                        if "not possible for an entity that requires sessions" in str(e):
                            # Queue is session-enabled: iterate available sessions
                            logger.info(
                                "Queue '%s' requires sessions; iterating sessions",
                                queue_name,
                            )
                            records.clear()
                            last_sequence = start_sequence
                            seen_sessions: set[str] = set()
                            max_empty_attempts = 3
                            empty_attempts = 0

                            while empty_attempts < max_empty_attempts:
                                try:
                                    with self._client.get_queue_receiver(
                                        queue_name,
                                        session_id=ServiceBusSessionFilter.NEXT_AVAILABLE,
                                        max_wait_time=self.max_wait_time,
                                    ) as session_receiver:
                                        sid = session_receiver.session.session_id
                                        if sid in seen_sessions:
                                            empty_attempts += 1
                                            continue
                                        seen_sessions.add(sid)
                                        empty_attempts = 0

                                        last_sequence = self._peek_all_from_receiver(
                                            session_receiver,
                                            max_message_count,
                                            start_sequence,
                                            queue_name,
                                            records,
                                            label=f"peek_queue({queue_name}/session={sid})",
                                        )
                                except OperationTimeoutError:
                                    # No more sessions available
                                    break
                                except ServiceBusError as inner_e:
                                    if "timeout" in str(inner_e).lower():
                                        break
                                    raise

                            # Re-sort by sequence number so records are ordered
                            records.sort(key=lambda r: r["sequence_number"])
                        else:
                            raise

            except (ServiceBusAuthenticationError, ServiceBusAuthorizationError) as e:
                raise ValueError(
                    f"Authentication/authorization failed reading queue '{queue_name}': {e}"
                ) from e
            except ServiceBusError as e:
                raise RuntimeError(
                    f"Service Bus error reading queue '{queue_name}': {e}"
                ) from e

            elapsed = time.perf_counter() - t_start
            logger.info(
                "queue_messages[%s]: read %d records (%.2fs, %.0f msgs/sec)",
                queue_name,
                len(records),
                elapsed,
                len(records) / elapsed if elapsed > 0 else 0,
            )

            # Recompute last_sequence from actual records if we have any
            if records:
                last_sequence = max(r["sequence_number"] for r in records)

            return iter(records), {"sequence_number": last_sequence}

        def _read_subscription_messages(  # pylint: disable=too-many-locals
            self, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """Read messages from a topic subscription using peek (non-destructive)."""
            topic_name = table_options.get("topic_name")
            subscription_name = table_options.get("subscription_name")

            if not topic_name or not subscription_name:
                raise ValueError(
                    "topic_name and subscription_name are required for subscription_messages table"
                )

            max_message_count = int(table_options.get("max_message_count", "100"))
            start_sequence = start_offset.get("sequence_number", 0)

            last_sequence = start_sequence
            records = []
            page_count = 0
            t_start = time.perf_counter()

            try:
                with self._client.get_subscription_receiver(
                    topic_name, subscription_name
                ) as receiver:
                    messages = self._peek_messages_with_retry(
                        receiver,
                        max_message_count,
                        start_sequence + 1 if start_sequence else 0,
                        label=f"peek_sub({topic_name}/{subscription_name})",
                    )

                    while messages:
                        page_count += 1
                        for msg in messages:
                            record = self._message_to_record(msg)
                            record["topic_name"] = topic_name
                            record["subscription_name"] = subscription_name
                            last_sequence = msg.sequence_number
                            records.append(record)
                            if self.debug_mode:
                                logger.debug(
                                    "subscription_messages[%s/%s] seq=%d msg_id=%s",
                                    topic_name,
                                    subscription_name,
                                    msg.sequence_number,
                                    msg.message_id,
                                )

                        # Get next batch
                        messages = self._peek_messages_with_retry(
                            receiver,
                            max_message_count,
                            last_sequence + 1,
                            label=f"peek_sub({topic_name}/{subscription_name})",
                        )
            except (ServiceBusAuthenticationError, ServiceBusAuthorizationError) as e:
                raise ValueError(
                    f"Authentication/authorization failed reading "
                    f"subscription '{topic_name}/{subscription_name}': {e}"
                ) from e
            except ServiceBusError as e:
                raise RuntimeError(
                    f"Service Bus error reading subscription "
                    f"'{topic_name}/{subscription_name}': {e}"
                ) from e

            elapsed = time.perf_counter() - t_start
            logger.info(
                "subscription_messages[%s/%s]: read %d records in %d pages (%.2fs, %.0f msgs/sec)",
                topic_name,
                subscription_name,
                len(records),
                page_count,
                elapsed,
                len(records) / elapsed if elapsed > 0 else 0,
            )

            return iter(records), {"sequence_number": last_sequence}

        def _read_dead_letter_messages(  # pylint: disable=too-many-locals
            self, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """Read dead-lettered messages from queues or subscriptions."""
            source_type = table_options.get("source_type")
            if source_type not in ("queue", "subscription"):
                raise ValueError("source_type must be 'queue' or 'subscription'")

            max_message_count = int(table_options.get("max_message_count", "100"))
            start_sequence = start_offset.get("sequence_number", 0)

            last_sequence = start_sequence
            records = []
            page_count = 0
            t_start = time.perf_counter()

            if source_type == "queue":
                queue_name = table_options.get("queue_name")
                if not queue_name:
                    raise ValueError(
                        "queue_name is required when source_type is 'queue'"
                    )
                source_name = queue_name
                receiver_ctx = self._client.get_queue_receiver(
                    queue_name,
                    sub_queue=ServiceBusSubQueue.DEAD_LETTER,
                )
            else:
                topic_name = table_options.get("topic_name")
                subscription_name = table_options.get("subscription_name")
                if not topic_name or not subscription_name:
                    raise ValueError(
                        "topic_name and subscription_name are required when "
                        "source_type is 'subscription'"
                    )
                source_name = f"{topic_name}/{subscription_name}"
                receiver_ctx = self._client.get_subscription_receiver(
                    topic_name,
                    subscription_name,
                    sub_queue=ServiceBusSubQueue.DEAD_LETTER,
                )

            try:
                with receiver_ctx as receiver:
                    messages = self._peek_messages_with_retry(
                        receiver,
                        max_message_count,
                        start_sequence + 1 if start_sequence else 0,
                        label=f"peek_dlq({source_name})",
                    )

                    while messages:
                        page_count += 1
                        for msg in messages:
                            record = self._message_to_record(msg)
                            record["source_type"] = source_type
                            record["source_name"] = source_name
                            record["dead_letter_reason"] = msg.dead_letter_reason
                            record["dead_letter_error_description"] = (
                                msg.dead_letter_error_description
                            )
                            last_sequence = msg.sequence_number
                            records.append(record)
                            if self.debug_mode:
                                logger.debug(
                                    "dead_letter_messages[%s] seq=%d msg_id=%s reason=%s",
                                    source_name,
                                    msg.sequence_number,
                                    msg.message_id,
                                    msg.dead_letter_reason,
                                )

                        # Get next batch
                        messages = self._peek_messages_with_retry(
                            receiver,
                            max_message_count,
                            last_sequence + 1,
                            label=f"peek_dlq({source_name})",
                        )
            except (ServiceBusAuthenticationError, ServiceBusAuthorizationError) as e:
                raise ValueError(
                    f"Authentication/authorization failed reading dead letters from "
                    f"'{source_name}': {e}"
                ) from e
            except ServiceBusError as e:
                raise RuntimeError(
                    f"Service Bus error reading dead letters from "
                    f"'{source_name}': {e}"
                ) from e

            elapsed = time.perf_counter() - t_start
            logger.info(
                "dead_letter_messages[%s]: read %d records in %d pages (%.2fs, %.0f msgs/sec)",
                source_name,
                len(records),
                page_count,
                elapsed,
                len(records) / elapsed if elapsed > 0 else 0,
            )

            return iter(records), {"sequence_number": last_sequence}

        def _message_to_record(self, msg: Any) -> dict:  # pylint: disable=too-many-branches
            """Convert a ServiceBusReceivedMessage to a dictionary record."""
            # Handle message body with content-type awareness
            body = None
            try:
                body_bytes = b"".join(msg.body)

                # Check max body size
                if self.max_body_size > 0 and len(body_bytes) > self.max_body_size:
                    logger.warning(
                        "Message %s body size %d exceeds max_body_size %d, truncating",
                        msg.message_id,
                        len(body_bytes),
                        self.max_body_size,
                    )
                    body_bytes = body_bytes[: self.max_body_size]

                # Content-type-aware decoding
                content_type = (msg.content_type or "").lower()
                if "json" in content_type or "text" in content_type or "xml" in content_type:
                    # Text-based content types: decode as UTF-8
                    try:
                        body = body_bytes.decode("utf-8")
                    except UnicodeDecodeError:
                        body = base64.b64encode(body_bytes).decode("ascii")
                elif (
                    content_type.startswith("application/octet-stream")
                    or content_type.startswith("image/")
                ):
                    # Binary content types: always base64 encode
                    body = base64.b64encode(body_bytes).decode("ascii")
                else:
                    # Unknown / unset content type: try UTF-8 first, fallback to base64
                    try:
                        body = body_bytes.decode("utf-8")
                    except UnicodeDecodeError:
                        body = base64.b64encode(body_bytes).decode("ascii")
            except Exception as e:
                logger.warning(
                    "Failed to read message body for msg_id=%s: %s", msg.message_id, e
                )
                body = None

            # Handle application properties
            app_props = None
            if msg.application_properties:
                try:
                    props = {}
                    for k, v in msg.application_properties.items():
                        key = k.decode("utf-8") if isinstance(k, bytes) else str(k)
                        if isinstance(v, bytes):
                            try:
                                value = v.decode("utf-8")
                            except UnicodeDecodeError:
                                value = base64.b64encode(v).decode("ascii")
                        elif isinstance(v, (datetime,)):
                            value = v.isoformat()
                        elif v is None:
                            value = None
                        else:
                            value = v
                        props[key] = value
                    app_props = json.dumps(props)
                except Exception as e:
                    logger.warning(
                        "Failed to serialize application properties for msg_id=%s: %s",
                        msg.message_id,
                        e,
                    )
                    app_props = None

            return {
                "sequence_number": msg.sequence_number,
                "message_id": msg.message_id,
                "body": body,
                "content_type": msg.content_type,
                "correlation_id": msg.correlation_id,
                "subject": msg.subject,
                "reply_to": msg.reply_to,
                "reply_to_session_id": msg.reply_to_session_id,
                "to": msg.to,
                "time_to_live": str(msg.time_to_live) if msg.time_to_live else None,
                "session_id": msg.session_id,
                "partition_key": msg.partition_key,
                "scheduled_enqueue_time_utc": msg.scheduled_enqueue_time_utc,
                "enqueued_time_utc": msg.enqueued_time_utc,
                "expires_at_utc": msg.expires_at_utc,
                "enqueued_sequence_number": msg.enqueued_sequence_number,
                "dead_letter_source": msg.dead_letter_source,
                "delivery_count": msg.delivery_count,
                "lock_token": str(msg.lock_token) if msg.lock_token else None,
                "locked_until_utc": msg.locked_until_utc,
                "state": (
                    str(msg.state) if hasattr(msg, "state") and msg.state else None
                ),
                "application_properties": app_props,
            }

        def close(self) -> None:
            """Close all clients and release resources."""
            self._closed = True
            errors = []
            if self._client:
                try:
                    self._client.close()
                except Exception as e:
                    errors.append(f"ServiceBusClient.close(): {e}")
                finally:
                    self._client = None
            if self._admin_client:
                try:
                    self._admin_client.close()
                except Exception as e:
                    errors.append(f"ServiceBusAdministrationClient.close(): {e}")
                finally:
                    self._admin_client = None
            if self._credential and hasattr(self._credential, "close"):
                try:
                    self._credential.close()
                except Exception as e:
                    errors.append(f"Credential.close(): {e}")
                finally:
                    self._credential = None
            if errors:
                logger.warning("Errors during close: %s", "; ".join(errors))

        def __enter__(self):
            return self

        def __exit__(self, exc_type, exc_val, exc_tb):
            self.close()
            return False


    ########################################################
    # src/databricks/labs/community_connector/sparkpds/lakeflow_datasource.py
    ########################################################

    LakeflowConnectImpl = AzureServicebusLakeflowConnect
    # Constant option or column names
    METADATA_TABLE = "_lakeflow_metadata"
    TABLE_NAME = "tableName"
    TABLE_NAME_LIST = "tableNameList"
    TABLE_CONFIGS = "tableConfigs"
    IS_DELETE_FLOW = "isDeleteFlow"


    class LakeflowStreamReader(SimpleDataSourceStreamReader):
        """
        Implements a data source stream reader for Lakeflow Connect.
        Currently, only the simpleStreamReader is implemented, which uses a
        more generic protocol suitable for most data sources that support
        incremental loading.
        """

        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.lakeflow_connect = lakeflow_connect
            self.schema = schema

        def initialOffset(self):
            return {}

        def read(self, start: dict) -> (Iterator[tuple], dict):
            is_delete_flow = self.options.get(IS_DELETE_FLOW) == "true"
            # Strip delete flow options before passing to connector
            table_options = {
                k: v for k, v in self.options.items() if k != IS_DELETE_FLOW
            }

            if is_delete_flow:
                records, offset = self.lakeflow_connect.read_table_deletes(
                    self.options[TABLE_NAME], start, table_options
                )
            else:
                records, offset = self.lakeflow_connect.read_table(
                    self.options[TABLE_NAME], start, table_options
                )
            rows = map(lambda x: parse_value(x, self.schema), records)
            return rows, offset

        def readBetweenOffsets(self, start: dict, end: dict) -> Iterator[tuple]:
            # TODO: This does not ensure the records returned are identical across repeated calls.
            # For append-only tables, the data source must guarantee that reading from the same
            # start offset will always yield the same set of records.
            # For tables ingested as incremental CDC, it is only necessary that no new changes
            # are missed in the returned records.
            return self.read(start)[0]


    class LakeflowBatchReader(DataSourceReader):
        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.schema = schema
            self.lakeflow_connect = lakeflow_connect
            self.table_name = options[TABLE_NAME]

        def read(self, partition):
            all_records = []
            if self.table_name == METADATA_TABLE:
                all_records = self._read_table_metadata()
            else:
                all_records, _ = self.lakeflow_connect.read_table(
                    self.table_name, None, self.options
                )

            rows = map(lambda x: parse_value(x, self.schema), all_records)
            return iter(rows)

        def _read_table_metadata(self):
            table_name_list = self.options.get(TABLE_NAME_LIST, "")
            table_names = [o.strip() for o in table_name_list.split(",") if o.strip()]
            all_records = []
            table_configs = json.loads(self.options.get(TABLE_CONFIGS, "{}"))
            for table in table_names:
                metadata = self.lakeflow_connect.read_table_metadata(
                    table, table_configs.get(table, {})
                )
                all_records.append({TABLE_NAME: table, **metadata})
            return all_records


    class LakeflowSource(DataSource):
        """
        PySpark DataSource implementation for Lakeflow Connect.
        """

        def __init__(self, options):
            self.options = options
            # TEMPORARY: LakeflowConnectImpl is replaced with the actual implementation
            # class during merge. See the placeholder comment at the top of this file.
            self.lakeflow_connect = LakeflowConnectImpl(options)

        @classmethod
        def name(cls):
            return "lakeflow_connect"

        def schema(self):
            table = self.options[TABLE_NAME]
            if table == METADATA_TABLE:
                return StructType(
                    [
                        StructField(TABLE_NAME, StringType(), False),
                        StructField("primary_keys", ArrayType(StringType()), True),
                        StructField("cursor_field", StringType(), True),
                        StructField("ingestion_type", StringType(), True),
                    ]
                )
            else:
                return self.lakeflow_connect.get_table_schema(table, self.options)

        def reader(self, schema: StructType):
            return LakeflowBatchReader(self.options, schema, self.lakeflow_connect)

        def simpleStreamReader(self, schema: StructType):
            return LakeflowStreamReader(self.options, schema, self.lakeflow_connect)


    spark.dataSource.register(LakeflowSource)
